### ISSUE TITLE
zips in s3 bucket are corrupted

### ISSUE THREAD

**Issue by d3m3tr1s** [DanielHindi/aws-s3-zipper#3]
Hello Daniel, I'm using your tool to zip images stored inside s3 bucket using your code as part of AWS Lambda, and facing the problem that for the larger images sets resulting zip is being corrupted
I set Lambda memory limit to the max possible by Amazon 1536 MB, and still having this issue even though cloud watch log shows that lambda call used 300-500 MB and it reports successful completion, zip is being created, though corrupted. When I repeat same with no more than 4-5 images with size 4-5 MB each, it creates healthy zip.

Any suggestion is highly appreciated.

Thank you for you great tool!

**Comment by DanielHindi** [comment]
So I use this module on a daily basis and zips up hundreds of megabytes of images yet in smaller zip increments. 

I'm using npm/archiver to zip. It seems there are updated on [archiver] that may solve this. It needs to be tested. 

That being said, you think 100-200 images at 2-5mb each would be a good test?

**Comment by d3m3tr1s** [comment]
Thank you for the tip, will try to update archiver module. 

Do you use this module wrapped into AWS Lambda function?

As side note I had to change this line

https://github.com/DanielHindi/aws-s3-zipper/blob/master/index.js#L187

to this 

`var tempFile = '/tmp/__' + Date.now() + '.zip';`

to make it work in AWS Lambda,  as tmp directory is the only writable place for lambdas

**Comment by DanielHindi** [comment]
No i dont use it in Lambda... its triggered in an api. 

if you make the tempFile configurable and send it in a pull request I'll accept it

**Comment by n7best** [comment]
@d3m3tr1s @DanielHindi 
https://github.com/DanielHindi/aws-s3-zipper/blob/master/index.js#L265
I think this line assume all the file will be zip in that timeframe (1s might be fine for small zip files)
should use zip.on('finish') instead to avoid corruption.

**Comment by d3m3tr1s** [comment]
Thank you for the tip, @n7best !

**Comment by DanielHindi** [comment]
The call back should only happen when the file has been zipped and released the problem is the module keeps a lock on the file for a few moments after the callback. Thats why i put a breathe time before moving on

**Comment by n7best** [comment]
https://github.com/DanielHindi/aws-s3-zipper/blob/master/index.js#L144
finalize or append from archiver does not guarantee the file is zipped.

**Comment by DanielHindi** [comment]
Any suggestions?

**Comment by n7best** [comment]
I test all three, not sure why, only `finish` works for me. My files are pretty large.

**Comment by DanielHindi** [comment]
I believe 1.0.1 has the potential to fix your issue
