### ISSUE TITLE
Cant Zip folders in a S3 Folder

### ISSUE THREAD

**Issue by hashim-sohail** [DanielHindi/aws-s3-zipper#7]
I am trying to zip a folder on S3 which contains further folders but the console says no files found.

**Comment by ddubyah** [comment]
Works for me. Have you set the 'recursive: true' option in the config?

**Comment by DanielHindi** [comment]
Hello Hashim,
I have this module working in production are you sure you have your options set correctly?
as @ddubyah mentioned `recursive=true` as well as the `path`

**Comment by hashim-sohail** [comment]
@ddubyah Didn't see that option. Thank you for the help. 
@DanielHindi It worked. Good job mate. (Y)
